### ISSUE TITLE
Create instructions for time-tracking 

### ISSUE THREAD

**Issue by mikepsinn** [anonymous-dao/draft-whitepaper#25]

**Comment by agelesspartners** [comment]
Where are these instructions located? Thanks!

**Comment by mikepsinn** [comment]
@agelesspartners 
Here you go!
https://github.com/anonymous-dao/draft-whitepaper/blob/cedb44dfca9dd50b1b1b84f0ea8ae77ab6ad321f/how-to/tracking-time-on-tasks.md

Also, if you ever have any trouble finding anything, the Github search box works pretty great:  
https://github.com/anonymous-dao/draft-whitepaper/search?q=time-tracking

That's a big reason I like the idea of trying to keep everything that we can in the repo, issues, or discussions here.  That way we only have to search one place. 

The only downsides are 
- the inconvenience of editing files and making pull requests
- lack of spreadsheets and nice sortable tables like Notion
